// Copyright 2023 Francesca <https://github.com/Francescatai>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/Francescatai/microblog_GOgRPC.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: microblog.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MicroblogClient is the client API for Microblog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MicroblogClient interface {
	ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
}

type microblogClient struct {
	cc grpc.ClientConnInterface
}

func NewMicroblogClient(cc grpc.ClientConnInterface) MicroblogClient {
	return &microblogClient{cc}
}

func (c *microblogClient) ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, "/v1.Microblog/ListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MicroblogServer is the server API for Microblog service.
// All implementations must embed UnimplementedMicroblogServer
// for forward compatibility
type MicroblogServer interface {
	ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error)
	mustEmbedUnimplementedMicroblogServer()
}

// UnimplementedMicroblogServer must be embedded to have forward compatible implementations.
type UnimplementedMicroblogServer struct {
}

func (UnimplementedMicroblogServer) ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (UnimplementedMicroblogServer) mustEmbedUnimplementedMicroblogServer() {}

// UnsafeMicroblogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MicroblogServer will
// result in compilation errors.
type UnsafeMicroblogServer interface {
	mustEmbedUnimplementedMicroblogServer()
}

func RegisterMicroblogServer(s grpc.ServiceRegistrar, srv MicroblogServer) {
	s.RegisterService(&Microblog_ServiceDesc, srv)
}

func _Microblog_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroblogServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Microblog/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroblogServer).ListUser(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Microblog_ServiceDesc is the grpc.ServiceDesc for Microblog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Microblog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Microblog",
	HandlerType: (*MicroblogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUser",
			Handler:    _Microblog_ListUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microblog.proto",
}
