# Config file for [Air](https://github.com/cosmtrek/air) in TOML format


root = "."
tmp_dir = "_output/microblog"


[build]
  args_bin = []
  bin = "_output/microblog/microblog.exe"
  cmd = "go build -o  ./_output/microblog/microblog.exe ./cmd/blog/main.go "
  delay = 0
  exclude_dir = []
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  rerun = false
  rerun_delay = 1000
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
